### ISSUE TITLE
MiniYak tests pass number instead of a BigNumber to `setERCBal`

### ISSUE THREAD

**Issue by fuzzylemma** [Snowball-Finance/axial-aggregator#1]
```
  5) YakAdapter - MiniYak
       swap
         mYak/Yak should be 1M - moon:
     TypeError: bn.toHexString is not a function
      at bigNumToBytes32 (test/helpers.js:5:57)
      at module.exports.setERC20Bal (test/helpers.js:114:39)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at runNextTicks (node:internal/process/task_queues:65:3)
      at listOnTimeout (node:internal/timers:526:9)
      at processTimers (node:internal/timers:500:7)
      at Context.<anonymous> (test/spec/adapters/miniYak.spec.js:74:13)

  6) YakAdapter - MiniYak
       swap
         YAK/mYAK should be 1μ - unmoon:
     TypeError: bn.toHexString is not a function
      at bigNumToBytes32 (test/helpers.js:5:57)
      at module.exports.setERC20Bal (test/helpers.js:114:39)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at runNextTicks (node:internal/process/task_queues:65:3)
      at listOnTimeout (node:internal/timers:526:9)
      at processTimers (node:internal/timers:500:7)
      at Context.<anonymous> (test/spec/adapters/miniYak.spec.js:97:13)
```

tests in miniYak pass numbers and are not BigNumber as expected by `bigNumToBytes32`.

**Comment by fuzzylemma** [comment]
made an upstream [PR](https://github.com/yieldyak/yak-aggregator/pull/41/commits/9385e3287d23088e094e0f302b20d5258c88c3bb) for this
